import Navbar from "./component/navbar";
import Sidebar from "./component/sidebar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" >
       
      <body>
        <div className="mainBox">
          <Sidebar/>
          <div className="rightContainer">
            <Navbar/>
         {children}
          </div>
    
        </div>
         </body>
    </html>
  );
}
